version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-prisma
    restart: always
    environment:
      # --- VARIABLES REQUERIDAS ---
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sistema_aeropuerto_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    
    ports:
      - "3306:3306"
      
    volumes:
      - db_data:/var/lib/mysql

# Define el volumen para la persistencia
volumes:
  db_data: