version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-prisma
    restart: always
    environment:
      # --- VARIABLES REQUERIDAS ---
      MYSQL_ROOT_PASSWORD: Clave2022@
      MYSQL_DATABASE: sistema_aeropuerto_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

# Define el volumen para la persistencia
volumes:
  db_data:
